version: '3.7'
services:
  elk:
    image: sandeepc0/elk-fidc
    container_name: elk-forgerock-idcloud
    deploy:
      resources:
        limits:
          memory: 8G
    environment:
      ES_HEAP_SIZE: "4G"
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  filebeat:
    image: sandeepc0/filebeat-fidc
    container_name: filebeat-forgerock-idcloud
    environment:
      ORIGIN: "${ORIGIN}"
      API_KEY_ID: "${API_KEY_ID}"
      API_KEY_SECRET: "${API_KEY_SECRET}"
      LOG_SOURCE: "${LOG_SOURCE}"

